kind: pipeline
name: androiddumps

steps:
- name: dumps
  image: ubuntu:18.04
  environment:
    PAT:
      from_secret: PAT
  commands:
  - rm -rf .git
  - mv *.sh $HOME
  - cd $HOME
  - bash start.sh https://phoenixnap.dl.sourceforge.net/project/xiaomi-eu-multilang-miui-roms//xiaomi.eu/MIUI-WEEKLY-RELEASES/21.2.4/xiaomi.eu_multi_HMNote8_21.2.4_v12-11.zip
